-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

create table
  collections (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    constraint collections_pkey primary key (id),
    constraint collections_name_key unique (name)
  );

create table
  sources (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    source text not null,
    collection character varying not null,
    description text not null default ''::text,
    sha512 text not null,
    constraint sources_pkey primary key (id),
    constraint sources_collection_fkey foreign key (collection) references collections (name) on update cascade on delete cascade
  );

create table
  documents (
    id uuid not null,
    content text not null,
    metadata jsonb not null,
    embedding extensions.vector not null,
    source_id bigint not null,
    collection text not null,
    sha512 text not null,
    source text not null,
    constraint documents_pkey primary key (id),
    constraint documents_collection_fkey foreign key (collection) references collections (name) on update cascade on delete cascade,
    constraint documents_source_id_fkey foreign key (source_id) references sources (id) on update cascade on delete cascade
  );



-- Create a function to search for documents
create function match_documents (
  query_embedding vector (1024),
  collection_name text,
  filter jsonb default '{}'
) returns table (
  id uuid,
  content text,
  metadata jsonb,
  source text,
  source_id bigint,
  collection text,
  similarity float
) language plpgsql as $$
#variable_conflict use_column
begin
  return query
  select
    id,
    content,
    metadata,
    source,
    source_id,
    collection,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where collection = collection_name and metadata @> filter
  order by documents.embedding <=> query_embedding;
end;
$$;





